theme: jekyll-theme-slate
title: Dash's homepage
description: Description

collections:
  writeups:
    output: true

pages:
  - title: Home
    url: /
  - title: Hack The Box Writeups
    url: /writeups/
